DROP DATABASE if exists NotesDB;
CREATE DATABASE NotesDB;

USE NotesDB;

CREATE TABLE Users(
id NUMBER  PRIMARY KEY, 
firstName VARCHAR2(30) CONSTRAINT SYS_USERS_FNAME_NN NOT NULL, 
lastName VARCHAR2(30) CONSTRAINT SYS_USERS_LNAME_NN NOT NULL, 
email VARCHAR2(100) CONSTRAINT SYS_USERS_EMAIL_NN NOT NULL CONSTRAINT SYS_USERS_EMAIL_UK UNIQUE, 
password VARCHAR2(30) CONSTRAINT SYS_USERS_PASSWORD_NN NOT NULL, 
sin NUMBER(9) CONSTRAINT SYS_USERS_SIN_NN NOT NULL CONSTRAINT SYS_USERS_SIN_UK UNIQUE);

ALTER TABLE USERS

ADD CONSTRAINT SYS_USERS_SIN_CK CHECK (sin Like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'); 

commit;
